[package]
name = "program"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "3.0.0"

[dev-dependencies]
solana-program-test = "3.0.7"
solana-sdk = "3.0.0"

[lib]
crate-type = ["cdylib", "lib"]
